export const ru = {
  common: {
    actions: {
      create: "Создать",
      edit: "Редактировать",
      delete: "Удалить",
      save: "Сохранить",
      cancel: "Отмена",
      open: "Открыть",
      back: "Назад",
      publish: "Опубликовать",
      archive: "Архивировать",
      addExercise: "Добавить упражнение",
      remove: "Удалить",
      retry: "Повторить",
      toList: "К списку",
      forward: "Вперед",
      clearCover: "Очистить обложку",
      clearAvatar: "Очистить аватар",
      addLink: "Добавить ссылку",
      saveProfile: "Сохранить профиль",
      close: "Закрыть",
    },
    labels: {
      status: "Статус",
      description: "Описание",
      title: "Название",
      updatedAt: "Дата обновления",
      createdAt: "Дата создания",
      version: "Версия",
      actions: "Действия",
      frequency: "Частота",
      level: "Уровень",
      published: "Опубликовано",
      workouts: "Тренировки",
      program: "Программа",
      programs: "Программы",
      versions: "Версии",
      exercises: "Упражнения",
      search: "Поиск",
      restSeconds: "Отдых (сек)",
      notes: "Примечания",
      sets: "Подходы",
      repsMin: "Повторы (мин)",
      repsMax: "Повторы (макс)",
      targetRpe: "Целевой RPE",
      dayOrder: "День",
      coachNote: "Заметка тренера",
      versionNumber: "Номер версии",
      frequencyPerWeek: "Тренировок в неделю",
      coverMedia: "Обложка",
      influencer: "Инфлюэнсер",
      goals: "Цели",
      updated: "Обновлено",
      programId: "ID программы",
      allPrograms: "Все программы",
      ownerType: "Тип владельца",
      publishedVersion: "Опубликованная версия",
      page: "Страница",
      elements: "элементов",
      items: "элементов",
    },
    placeholders: {
      searchPrograms: "Поиск программ",
      searchVersions: "Поиск версий",
      searchWorkouts: "Поиск тренировок",
      searchExercise: "Поиск упражнения",
      selectStatus: "Выберите статус",
      selectProgram: "Выберите программу",
      selectVersion: "Выберите версию",
      selectProgramFirst: "Сначала выберите программу",
      titleExampleProgram: "Например: Летний рельеф",
      descriptionProgram: "Кратко опишите идею программы",
      goalsComma: "Например: снижение веса, мобильность, выносливость",
      workoutTitle: "Например: Верх тела A",
      level: "Например: Начальный / Средний",
      exerciseNameOrCode: "Название или код",
      searchInfluencer: "Поиск инфлюэнсера по имени",
      selectInfluencer: "Выберите инфлюэнсера",
      loadingInfluencers: "Загружаем инфлюэнсеров...",
    },
    states: {
      notFound: "Не найдено",
      empty: "Пусто",
      loading: "Загрузка...",
      notPermitted: "Недостаточно прав",
      dash: "—",
    },
    status: {
      DRAFT: "Черновик",
      PUBLISHED: "Опубликовано",
      ARCHIVED: "В архиве",
      ALL: "Все статусы",
    },
  },
  sidebar: {
    admin: {
      dashboard: "Панель управления",
      media: "Медиафайлы",
      muscles: "Мышцы",
      equipment: "Оборудование",
      exercises: "Упражнения",
      programs: "Программы",
      workouts: "Тренировки",
      progression: "Прогрессия",
    },
    influencer: {
      dashboard: "Панель управления",
      media: "Медиафайлы",
      exercises: "Упражнения",
      programs: "Программы",
      workouts: "Тренировки",
      progression: "Прогрессия",
      profile: "Профиль",
    },
  },
  programs: {
    tabs: {
      info: "Информация",
      workouts: "Тренировки",
    },
    title: "Программы",
    createProgram: "Создать программу",
    versionWorkouts: "Тренировки версии",
    publishByAdmin: "Публикация версии выполняется администратором.",
    publishDialogDescription:
      "Опубликовать эту версию? После публикации она будет доступна пользователям.",
    publishing: "Публикация...",
    page: {
      loading: "Загружаем программы...",
      loadError: "Не удалось загрузить программы",
      createError: "Не удалось создать программу",
      createSuccessTitle: "Программа успешно создана",
      createSuccessDescription: "Метаданные программы сохранены.",
      emptyTitle: "Программы не найдены",
      emptyDescription: "Создайте первую программу.",
      emptyDescriptionSearch: "Измените поисковый запрос.",
    },
    versions: {
      table: {
        openWorkouts: "Тренировки",
      },
      createVersion: "Создать версию",
      createSuccess: "Версия успешно создана.",
      updateSuccess: "Версия сохранена.",
      archiveSuccess: "Версия архивирована.",
      archiveConfirmTitle: "Архивировать версию?",
      archiveConfirmDescription:
        "Версия будет переведена в статус «В архиве». Это действие нельзя отменить на этом экране.",
      loadError: "Не удалось загрузить версии",
      loading: "Загружаем версии...",
      apiUnavailable: "API версий недоступен",
      createError: "Не удалось создать версию",
      updateError: "Не удалось сохранить версию",
      archiveError: "Не удалось архивировать версию",
      emptyTitle: "Версии не найдены",
      emptyDescription: "Попробуйте изменить параметры поиска.",
      dialogDescription: "Настройте метаданные версии программы.",
    },
    details: {
      loadError: "Не удалось загрузить программу",
      loading: "Загружаем программу...",
      emptyServer: "Пустой ответ от сервера.",
      saveSuccessTitle: "Программа сохранена",
      saveSuccessDescription: "Изменения метаданных успешно применены.",
      saveError: "Не удалось сохранить изменения",
      publishSuccessTitle: "Версия опубликована",
      publishSuccessDescription: "Программа обновлена и версия опубликована.",
      publishError: "Не удалось опубликовать версию",
      readOnlyTitle: "Детали программы",
      readOnlyDescription: "Редактирование недоступно для текущей роли.",
      versionsUnavailable: "Версии недоступны",
      versionsApiUnavailable: "API версий недоступен",
      updateNotSupported: "Редактирование недоступно для этой роли",
      publishNotSupported: "Публикация недоступна для этой роли",
      createNotSupported: "Создание версии недоступно для этой роли",
      updateVersionNotSupported: "Редактирование версии недоступно для этой роли",
      archiveNotSupported: "Архивация версии недоступна для этой роли",
    },
    form: {
      goalsHint: "через запятую",
      influencerRequired: "Укажите инфлюэнсера",
      noInfluencers: "Инфлюэнсеры не найдены.",
      statusSelect: "Выберите статус",
      saving: "Сохраняем...",
      titleRequired: "Укажите название программы",
      invalidMediaId: "Некорректный ID медиа",
      versionNumberValidation: "Номер версии должен быть больше 0",
    },
    scope: {
      adminSubtitle: "Управление программами платформы.",
      influencerSubtitle: "Управление программами инфлюэнсера.",
      searchByTitle: "Поиск по названию программы",
      adminInfluencerRequired: "Для создания программы администратором нужен influencerId",
      versionProgramRequired: "Для поиска версий требуется programId",
    },
    versionPicker: {
      selectVersion: "Выберите версию",
      createVersion: "Создать версию",
      noVersionsTitle: "Версии программы отсутствуют",
      noVersionsDescription: "Создайте версию, чтобы перейти к настройке тренировок.",
    },
  },
  workouts: {
    title: "Тренировки",
    listTitle: "Тренировки версии",
    listSubtitle: "Управление шаблонами тренировок для выбранной версии программы.",
    createWorkout: "Создать тренировку",
    openVersions: "Открыть версии",
    backToProgram: "К программе",
    backToWorkouts: "К тренировкам",
    loadError: "Не удалось загрузить тренировки",
    loadingPrograms: "Загружаем программы...",
    loadProgramsError: "Не удалось загрузить программы",
    loadingExercises: "Загружаем упражнения...",
    emptyTitle: "Тренировки не найдены",
    emptyDescription: "Создайте первую тренировку для этой версии.",
    created: "Тренировка успешно создана.",
    updated: "Тренировка сохранена.",
    deleted: "Тренировка удалена.",
    createError: "Не удалось создать тренировку",
    updateError: "Не удалось сохранить тренировку",
    deleteError: "Не удалось удалить тренировку",
    deleteConfirmTitle: "Удалить тренировку?",
    deleteConfirmDescription:
      "Вы действительно хотите удалить эту тренировку? Это действие нельзя отменить.",
    detailsLoadError: "Не удалось загрузить тренировку",
    detailsNotFound: "Тренировка не найдена",
    detailsEmptyServer: "Пустой ответ сервера.",
    detailsSubtitle: "Программа {programId} · Версия {programVersionId}",
    exerciseCount: "упражнений",
    exerciseAdded: "Упражнение добавлено в тренировку.",
    exerciseUpdated: "Параметры упражнения сохранены.",
    exerciseRemoved: "Упражнение удалено из тренировки.",
    exerciseAddError: "Не удалось добавить упражнение",
    exerciseUpdateError: "Не удалось сохранить параметры упражнения",
    exerciseDeleteError: "Не удалось удалить упражнение",
    reorderError: "Не удалось сохранить порядок упражнений",
    noExercises: "В этой тренировке пока нет упражнений.",
    dragToReorder: "Перетащите для изменения порядка",
    saveParams: "Сохранить параметры",
    removing: "Удаление...",
    adding: "Добавление...",
    notFound: "Ничего не найдено.",
    hubSubtitle: "Быстрый доступ к тренировкам по выбранной программе и версии.",
    emptySearchHint: "Попробуйте изменить поисковый запрос.",
    selectProgramTitle: "Выберите программу",
    selectProgramDescription:
      "Выберите программу и версию сверху, чтобы открыть редактор тренировок.",
    selectVersionTitle: "Выберите версию",
    selectVersionDescription: "После выбора версии откроется список тренировок и кнопка «Создать».",
    unknownSourceMine: "Мои",
    unknownSourceInfluencer: "Инфлюэнсер",
    unknownSourceBase: "База",
    selectExerciseValidation: "Выберите упражнение",
    addExerciseDescription: "Найдите упражнение и задайте стартовые параметры.",
    fillTemplateParams: "Заполните базовые параметры шаблона тренировки.",
    unnamedWorkout: "Без названия",
    workoutBreadcrumbFallback: "Тренировка",
    minSetsValidation: "Минимум 1 подход",
    dayOrderValidation: "Номер дня должен быть больше 0",
    max200Validation: "Максимум 200 символов",
    max2000Validation: "Максимум 2000 символов",
    dragToReorderHint: "Перетащите для изменения порядка",
  },
  layout: {
    topbarTitle: "Панель управления Fitfluence",
    userFallback: "Пользователь",
    logout: "Выйти",
  },
  profile: {
    titleCreate: "Создание профиля",
    titleEdit: "Редактирование профиля",
    subtitleCreate: "Заполните профиль, чтобы продолжить работу в кабинете инфлюэнсера.",
    subtitleEdit: "Обновите данные профиля инфлюэнсера.",
    loading: "Загружаем профиль инфлюэнсера...",
    loadError: "Не удалось загрузить профиль",
    saveSuccessTitle: "Профиль сохранен",
    saveSuccessDescription: "Данные профиля инфлюэнсера обновлены.",
    saveErrorTitle: "Ошибка сохранения",
    saveErrorDescription: "Не удалось сохранить профиль",
    uploadSuccessTitle: "Аватар загружен",
    uploadSuccessDescription: "Медиа успешно загружено и выбрано для аватара.",
    uploadErrorTitle: "Ошибка загрузки",
    uploadErrorDescription: "Не удалось загрузить файл",
    displayName: "Отображаемое имя",
    displayNamePlaceholder: "Ваше отображаемое имя",
    bio: "О себе",
    bioPlaceholder: "Коротко о себе",
    avatar: "Аватар",
    uploadFromDevice: "Загрузите файл с устройства",
    uploading: "Загружаем файл...",
    avatarPreviewAlt: "Предпросмотр аватара",
    socialLinks: "Социальные ссылки",
    socialLinksEmpty: "Ссылки не добавлены.",
    socialLinkTypePlaceholder: "Тип (instagram, youtube)",
    socialLinkUrlPlaceholder: "https://example.com/profile",
    linkTypeRequired: "Укажите тип ссылки",
    linkUrlInvalid: "Введите корректный URL",
    avatarIdInvalid: "Некорректный ID медиа",
    saving: "Сохраняем...",
  },
} as const;
